# database:
#   type: mysql or sqlite
#   username: name of the mysql database user
#   password: mysql user's password
#   host: mysql host name or ip
#   port: mysql port, default is 3306
#   database: name of the database used
#   table: name of the table used
# converter: EXPERIMENTAL - be sure to make a backup first!
#   REMEMBER: converter only works for MySQL databases, so be sure to use MySQL for both previous plugin and this plugin as well before converting
#   cc: find "db-prefix" setting from your old Creative Control config and copy the value here
#   sc: find "MySQL.TableName" setting from your old ShareControl config and copy the value here
# general:
#   save-interval: time in ticks (20 ticks = 1 second) between each sync to database (recommended: 1200 - 36000)
#   track: whether to save blocks/items placed in creative mode and remove their drops
#   worldedit: REQUIRES WORLDEDIT
#     enabled: whether to save blocks/items placed with WorldEdit in creative mode and remove their drops
#     extended: whether to save blocks/items placed with WorldEdit in any gamemode and remove their drops (above must be true)
#   separate-invs: whether creative and survival/adventure inventories should be separate
#   remove-invalid-items: whether to remove invalid items (with custom NBT) from creative players' inventories (REQUIRES ProtocolLib)
#     invalid items include BARRIER, COMMAND, COMMAND_CHAIN, COMMAND_REPEATING, COMMAND_MINECART, HUGE_MUSHROOM_1, HUGE_MUSHROOM_2, 
#      MOB_SPAWNER, GRASS_PATH, STRUCTURE_BLOCK, STRUCTURE_VOID, DRAGON_EGG
#   disabled-worlds:
#     list of worlds this plugin is disabled in
#     by default, creative players can't travel to worlds listed here
#     if you want to allow everything, delete the list and put "[]" after "disabled-worlds:"
#   command:
#     description: the main command description
#     aliases: other forms of the main command
#   regions: REQUIRES WORLDGUARD
#     enabled: whether using creative should be limited to certain region(s)
#     whitelist: list of WorldGuard region names where entering creative mode (via the main command)
#      and placing blocks/items in creative mode is allowed 
#   armor:
#     enabled: whether to automatically put non-removable colored armor on creative players
#     color: leather armor color value (from this site, for example: https://minecraftcommand.science/armor-color)
#   permissions:
#     enabled: whether or not to give special permissions to players in creative mode
#     list:
#       list of permissions that are added, when player is put into creative mode, and removed, when their creative mode is removed
#       to remove a permission instead of adding, just add "-" in front of it
#   disable:
#     interact:
#       inventories: whether to disable interaction with inventories (chests, hoppers, villagers etc)
#       entities: whether to disable interaction (right-clicking) with entities (breeding, armor stands, touch holograms etc, excluding item frames)
#       breeding: whether to disable animal breeding (this setting won't affect anything if above "entities:" is set to "true") - 1.10+ ONLY
#     item:
#       drop: whether to disable item dropping in creative mode 
#       pickup: whether to disable item pickup in creative mode
#       throw: whether to disable throwing/shooting items (splash potions, eggs, arrows etc)
#     commands:
#       list of commands which are disabled for creative players
#       supports powerful RegEx - http://regexr.com/
#       if you want to allow everything, delete the list and put "[]" after "commands:"
#     combat:
#       pvp: whether to disable player vs player combat
#       pve: whether to disable player vs entity combat
#     creation:
#       wither: whether to disable creating Wither from creative blocks
#       snow-golem: whether to disable creating Snow Golem from creative blocks
#       iron-golem: whether to disable creating Iron Golem from creative blocks
# messages:
#   if you wish to disable a message, replace it with ''
#   text formatting is supported: http://minecraft.gamepedia.com/Formatting_codes
#   %mills% is replaced with time taken by the task (only on db-done)
#   %blocks% is replaced with number of blocks processed by the task (only on db-added, db-removed, db-loaded)
#   %material% is replaced with material name of the block (only on block-added, block-removed, block-info-true, block-info-false)
#   %total% is replaced with total blocks and entities count (only on block-stats)
# blacklists: 
#   available values are listed here (for the latest Spigot version): https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#   if you want to allow everything, delete the list and put "[]" after "use:", "interact:" and/or "break:"
#   place:
#     list of items that creative players cannot place
#   interact:
#     in-hand:
#       list of items that, while holding in hand, creative players cannot use/interact with anything
#       also blocks items from being placed, but for that use "blacklists.place"
#       INK_SACK is blacklisted, because bone meal is also an Ink Sac and it can be used to grow trees too quickly 
#       EYE_OF_ENDERs, for example, are blacklisted because they drop or become a part of the End portal
#        when shot, which is interfering with survival experience
#       if you use version below 1.10 and want to disable animal breeding (but not interacting with entities),
#        this is a good place to list items used in breeding
#       if you use 1.8, comment out (add '#' in front) or delete SPLASH_POTION and LINGERING_POTION,
#        because they will throw errors, and add POTION
#     on-ground:
#       list of items that, while placed in the world, creative players cannot use/interact with
#       SIGNs are blacklisted, because some shop plugins allow selling items by clicking on a sign
#       JUKEBOXes and FLOWER_POTs are blacklisted, because they could be used to smuggle stuff into survival mode
#   break:
#     list of items that creative players cannot break
# whitelist:
#   available values are listed here (for the latest Spigot version): https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#   if you want to exclude a block/item from being tracked, add it into the list (see blacklist for example format)
#   if you want to track everything, leave it as default: "[]" after "whitelist:"
#
database:
  type: sqlite
  username: root
  password: ''
  host: localhost
  port: 3306
  database: rc_database
  table: rc_table

converter:
  cc: cc_
  sc: blocks

general:
  save-interval: 6000
  track: true
  worldedit:
    enabled: false
    extended: false
  separate-invs: true
  remove-invalid-items: false
  disabled-worlds:
  - 'survival'
  command:
    description: 'Allows player to switch between creative and default gamemodes.'
    aliases:
    - 'restrictedcreative'
    - 'creative'
    - 'gmc'
    - 'gm1'
    - 'gm'
  regions:
    enabled: false
    whitelist:
    - 'building_competition'
  armor:
    enabled: true
    color: 16711680
  permissions:
    enabled: false
    list:
    - 'prefix.creative'
    - '-prefix.survival'
  disable:
    interact:
      inventories: true
      entities: true
      breeding: true
    item:
      drop: true
      pickup: true
      throw: true
    commands:
    - '(.*)(buy|sell)(.*)'
    - '(.*)(chest)(.*)'
    combat:
      pvp: true
      pve: true
    creation:
      wither: true
      snow-golem: true
      iron-golem: true
      
messages:
  prefix: '&2&lCreative > '
  no-permission: '&cYou don''t have enough permissions to do that!'
  no-console: '&cThis command can only be used in-game.'
  disabled: '&cYou can''t do that in creative mode.'
  disabled-interact: '&cYou can''t do that, because that was modified in creative mode.'
  reloaded: '&aConfig reloaded!'
  db-load: '&eLoading data from database...'
  db-save: '&eSaving data to database...'
  db-added: '&eAdded %blocks% new blocks to database.'
  db-removed: '&eDeleted %blocks% old blocks from database.'
  db-deleted: '&eDeleted database. Full restart is required for changes to take effect.'
  db-loaded: '&eLoaded %blocks% blocks from database!'
  db-done: '&aDone! Took %mills%ms'
  creative-on: '&aCreative mode enabled!'
  creative-off: '&aCreative mode disabled!'
  wrong-convert: '&cCorrect usage: /rc convert <cc|gmi|sql>'
  wrong-block: '&cCorrect usage: /rc block <add|remove|info|stats>'
  cancel: '&cCancelled!'
  block-add: '&aRight-click a block/entity you want to add to the database. Type "/rc block add" again to cancel.'
  block-added: '&aAdded %material% to the database!'
  block-remove: '&aRight-click a block/entity you want to remove from the database. Type "/rc block remove" again to cancel.'
  block-removed: '&aRemoved %material% from the database!'
  block-info: '&aRight-click a block/entity you want to know more about. Type "/rc block info" again to cancel.'
  block-info-true: '&aBlock/entity %material% is placed in creative mode!'
  block-info-false: '&aBlock/entity %material% is not placed in creative mode.'
  disabled-region: '&cYou can''t do that outside the allowed region.'
  block-stats: '&eTotal creative placed blocks and entities: %total%'

blacklists:
  place:
  - 'BEDROCK'
  - 'ENDER_PORTAL_FRAME'
  - 'TNT'
  - 'SAPLING'
  interact:
    in-hand:
    - 'SPLASH_POTION'
    - 'LINGERING_POTION' 
    - 'MONSTER_EGG'
    - 'FLINT_AND_STEEL'
    - 'FIREBALL'
    - 'EXP_BOTTLE'
    - 'INK_SACK'
    - 'EYE_OF_ENDER'
    - 'EGG'
    - 'LAVA_BUCKET'
    on-ground:
    - 'JUKEBOX'
    - 'FLOWER_POT'
    - 'SIGN_POST'
    - 'WALL_SIGN'
  break:
  - 'BEDROCK'
  - 'ENDER_PORTAL_FRAME'
  
whitelist: []
